name: Run integration tests with Bigquery

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "integration_test_bq" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
          
      # Install dbt
      - name: Install dbt with Bigquery adapter
        run: pip install dbt-bigquery==1.6.1
      
      # Set up dbt profiles for test
      - name: Create profiles.yml
        run: |
          echo "datamocktool:
                target: dev
                outputs:
                  dev:
                    type: bigquery
                    method: service-account-json
                    project: ${{ secrets.GCP_PROJECT }}
                    dataset: jaffle_shop
                    threads: 1
                    # These fields come from the service account json keyfile
                    keyfile_json:
                ${{ secrets.GCP_SA_KEYFILE_JSON }}
                " > ./integration_tests/profiles.yml
      
      - name: Run integration tests
        run: | 
          cd integration_tests 
          ./run_integration_tests.sh
